//
// Created by bogdan on 18.11.2023.
//

#ifndef AIR_TRAFFIC_CONTROLLER_ENUMS_H
#define AIR_TRAFFIC_CONTROLLER_ENUMS_H

enum AIRPLANE_FLAGS {
    SAFE_COLLISION_DISTANCE = 0,
    DANGER_COLLISION_DISTANCE = 1,
};

#endif //AIR_TRAFFIC_CONTROLLER_ENUMS_H
